language: c

env:
    - AMXXVERSION=1.8.3-dev-git5175
   # - AMXXVERSION=1.8.2

matrix:
    fast_finish: true
    allow_failures:
    - env: AMXXVERSION=1.8.3-dev-git5175

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    - wget -q "https://www.amxmodx.org/amxxdrop/1.8/amxmodx-$AMXXVERSION-base-linux.tar.gz" -O amxmodx.tar.gz
    - tar -xzf amxmodx.tar.gz
    - cd addons/amxmodx/scripting/
    - chmod +x amxxpc32.so
    - chmod +x compile.sh

script:
    - ./compile.sh ChatsAdditions_API.sma
    - ./compile.sh CA_Gag.sma
    - ./compile.sh CA_Mute.sma
    - ./compile.sh CA_NeedKills.sma
